### ISSUE TITLE
between? defined twice

### ISSUE THREAD

**Issue by err** [rentpath/rp-query-clj#1]
https://github.com/rentpath/rp-query-clj/blob/master/src/rp/query/dsl_spec.clj#L20
https://github.com/rentpath/rp-query-clj/blob/master/src/rp/query/dsl_spec.clj#L42

**Comment by semperos** [comment]
@err Nice catch, thank you!

**Comment by err** [comment]
i'll open a PR unless you're already there

**Comment by semperos** [comment]
Fixed by https://github.com/rentpath/rp-query-clj/commit/cfa8b21ff358e588f209a473bd902fc94a8c26e8
